apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: example-task-3
spec:
  steps:
    - image: registry.access.redhat.com/ubi8/ubi:latest
      script: |
        #!/usr/bin/env bash
        echo "Hello from task 3"